version: "3.1"

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: plottwisters
      MYSQL_USER: U04
      MYSQL_PASSWORD: plottwisters
      MYSQL_DATABASE: U04-plottwisters
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  mariadb_data: